---
image: docker:latest

stages:
  - build
  - test
  - release 

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

test:
  stage: test
  variables:
    POSTGRES_IMAGE: postgres:9.6
  script:
    - docker pull $POSTGRES_IMAGE
    - >
      docker run -d --name pg
      -e "POSTGRES_USER=pg"
      -e "POSTGRES_PASSWORD=pg"
      $POSTGRES_IMAGE
    - >
      until
      docker run --rm --link pg -e "PGPASSWORD=pg" $POSTGRES_IMAGE
      psql -U pg -h pg -d pg -c "select 1";
      do
      sleep 1;
      done
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - >
      docker run
      --link pg
      -e "TEST_PG_DSN=postgresql://pg:pg@pg/pg"
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      cpanm -v --test-only .

release:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  allow_failure: true
  only:
    - master
