---
image: docker:latest

stages:
  - build
  - test
  - release 

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

test:
  stage: test
  variables:
    ELASTICSEARCH_IMAGE: $CI_REGISTRY/le-garff-yoann/zombodb:elasticsearch-latest
    POSTGRES_IMAGE: $CI_REGISTRY/le-garff-yoann/zombodb:postgres-latest
  script:
    - docker pull $ELASTICSEARCH_IMAGE
    - docker pull $POSTGRES_IMAGE
    - >
      docker run -d --name es
      -e "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      $ELASTICSEARCH_IMAGE
    - sleep 10 
    - >
      docker run -d --name pg --link es
      -e "POSTGRES_USER=pg"
      -e "POSTGRES_PASSWORD=pg"
      $POSTGRES_IMAGE
      postgres -c zombodb.default_elasticsearch_url=http://es:9200/
    - sleep 10
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - >
      docker run
      --link pg
      -e "TEST_PG_DSN=postgresql://pg:pg@pg/pg"
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      cpanm -v --test-only .

release:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  allow_failure: true
  only:
    - master
