#!perl

use Mojo::Base -strict;

use FindBin;

BEGIN {
    unshift @INC, $FindBin::Bin . '/../lib';
}

use Mojolicious::Commands;

Mojolicious::Commands->start_app('Clovershell');

=pod

=encoding utf8

=head1 NAME

clovershell - Run Clovershell

=head1 COPYRIGHT

Copyright (C) 2017-2018 Yoann Le Garff, Boquet Nicolas and Yann Le Bras

=head1 LICENSE

clovershell is licensed under the Apache License, Version 2.0

=cut
